CC = gcc
OBJECTS = main.o animation.o shaders.o entry.o geom.o
CFLAGS = -Wall -Wextra -ansi -pedantic -DWITH_DIRENT -DUSING_FREEGLUT
LDLIBS = -lglew32 -lfreeglut -lopengl32 -lglu32
RM = rm -f

.PHONY: all clean

all: jpspt geom_test

jpspt: $(OBJECTS)
	@echo LD $@
	@$(CC) $(LDFLAGS) $(OBJECTS) $(LDLIBS) -o jpspt

geom_test: geom_test.o geom.o

%.o: %.c
	@echo CC $@
	@$(CC) $(CFLAGS) -c -o $@ $<

clean:
	@echo CLEAN
	@$(RM) jpspt.exe geom_test.exe $(OBJECTS)
